allowBuilds:
  vue-demi: true
shellEmulator: true
trustPolicy: no-downgrade
onlyBuiltDependencies:
  - esbuild
  - vue-demi
minimumReleaseAgeExclude:
  - '@vue/language-core@3.3.6'
  - vite@8.1.2
  - vue-tsc@3.3.6
